### ISSUE TITLE
Built log: difference between 'Cancel' and 'Close' buttons?

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/tljh-repo2docker#24]
Logs could be viewed in a separate window when environment is under construction:
![image](https://user-images.githubusercontent.com/733861/82842940-b29ecf00-9edb-11ea-9c2b-a9801dab0b52.png)

I did not understand the purpose of `Cancel` and `Close` button. Maybe the later would be sufficient.

**Comment by jtpio** [comment]
It comes from the default JupyterHub modals that are reused in multiple places.

We can hide the cancel button by adding the following CSS:

```css
#show-logs-dialog .btn-default {
  display: none;
}
```

to: https://github.com/plasmabio/tljh-repo2docker/blob/658a8d2303b5f88f373b502ebd8e83d17fdbcd1b/tljh_repo2docker/static/css/style.css

**Comment by pierrepo** [comment]
Thanks. The `Cancel` button might let the user think it could cancel the built of the env.

**Comment by pierrepo** [comment]
I installed the whole dev environment. And indeed your proposal worked!

![image](https://user-images.githubusercontent.com/733861/86646112-44bbec00-bfdf-11ea-94d4-fae53dd55ed2.png)

**Comment by jtpio** [comment]
Fixed by https://github.com/plasmabio/tljh-repo2docker/pull/33
