### ISSUE TITLE
Add support for private repositories

### ISSUE THREAD

**Issue by jtpio** [plasmabio/tljh-repo2docker#27]
For now `tljh-repo2docker` can build environments from repositories that are publicly accessible.

However it would be useful if it could also build environments from private repositories.

BinderHub supports this use case with the [`git_credentials` option](https://binderhub.readthedocs.io/en/latest/reference/repoproviders.html?highlight=git_credentials#binderhub.repoproviders.RepoProvider).

The value is then passed as a `GIT_CREDENTIAL_ENV` environment variable to the builder (the `jupyter/repo2docker:master` Docker image): https://github.com/jupyterhub/binderhub/blob/3cb82fafa55d25e8fb6c6559423ffdef57919aa3/binderhub/build.py#L236

For `tljh-repo2docker`, we would need to pass these credentials using the `GIT_CREDENTIAL_ENV` environment variable to the command here:

https://github.com/plasmabio/tljh-repo2docker/blob/05ce3d589822797e2834301239e76f0950bd87a8/tljh_repo2docker/docker.py#L82-L96

Something like the following:

```python
cmd = [
    "GIT_CREDENTIAL_ENV=username=foo\npassword=bar",
    "jupyter-repo2docker",
    "--ref",
    ref,
    "--user-name",
    "jovyan",
    "--user-id",
    "1100",
    "--no-run",
    "--image-name",
    image_name,
    "--appendix",
    "\n".join(labels),
    repo,
]
```

The credentials could be specified in the form:

![add-new](https://user-images.githubusercontent.com/591645/80963115-9fce3880-8e0e-11ea-890b-c9b928f7edb1.png)

Or as a configurable for the `tljh_repo2docker` plugin.

**Comment by jtpio** [comment]
Documentation to access private repositories for BinderHub:

https://binderhub.readthedocs.io/en/latest/zero-to-binderhub/setup-binderhub.html?accessing-private-repositories#accessing-private-repositories

The token can be generated from the GitLab UI:

![image](https://user-images.githubusercontent.com/591645/84685883-48f26d80-af3b-11ea-818e-5be9f48facf6.png)

**Comment by pierrepo** [comment]
And I guess similar things could be done with the GitHub UI:

![image](https://user-images.githubusercontent.com/733861/84699372-af828600-af51-11ea-9b70-c986074d46d2.png)

**Comment by SylvainCorlay** [comment]
Optional extra git credentials could be in a `<detail>` section of the form.

There could be an option to fill the password with the hub authentication token for the case where we use the gitlab's SSO.
