### ISSUE TITLE
Mounting user home in docker

### ISSUE THREAD

**Issue by machar94** [plasmabio/tljh-repo2docker#30]
I was wondering whether, by default, the home directory of the user would be mounted to the running container. I was interested in using this plugin to specify a repo with a Julia installation and required Julia packages for a class. For each student, I would like them to have the same environment with all the same packages (1 docker image), but be able to run multiple containers that on start would mount their home directory so they could continue where they left off from last time. Additionally, would it also be possible to configure other folders to be mounted if I wanted to upload certain datasets to the server running The Littlest Jupyter Hub? Thank you for your help.

**Comment by jtpio** [comment]
Thanks @machar94.

Yes `tljh-repo2docker` can still be used to create the Docker image with the same packages.

Then the mounting of the home directory (and the other folders) can be done separately:

- with an additional [TLJH plugin](https://tljh.jupyter.org/en/latest/contributing/plugins.html). There is the [`tljh-plasma`]( https://github.com/plasmabio/plasma/blob/master/tljh-plasma/tljh_plasma/__init__.py) as an example
- or by providing extra configuration to TLJH: https://tljh.jupyter.org/en/latest/topic/escape-hatch.html?highlight=config#extending-jupyterhub-config-py

**Comment by jtpio** [comment]
Alternatively if there is only 1 environment you might want to use TLJH's default user environment directly: 

https://tljh.jupyter.org/en/latest/howto/env/user-environment.html

**Comment by machar94** [comment]
Thank you very much for your help! I will look into those further.

**Comment by jtpio** [comment]
You're welcome!

Don't hesitate to open a new issue if you want to discuss more.
