### ISSUE TITLE
Default branch name in repo

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/tljh-repo2docker#43]
GitHub recently changed [default branch name](https://github.com/github/renaming) from `master` to `main`.

The default branch name taken into account by `tljh-repo2docker` is `master`. Could we possibly try / look for `master` or `main` as default branch name?

**Comment by jtpio** [comment]
There was a similar discussion in the BinderHub repo: https://github.com/jupyterhub/binderhub/pull/1170
It could be interesting to follow the same approach (there might be more hints by following linked issues and PRs).

But maybe it would also be fine to simply default to `main` for `tljh-repo2docker`.

**Comment by jtpio** [comment]
> But maybe it would also be fine to simply default to `main` for `tljh-repo2docker`.

Or with `HEAD`: https://github.com/jupyterhub/binderhub/pull/1186

**Comment by pierrepo** [comment]
Woh this looks very clever!
