### ISSUE TITLE
HTTP 500: Internal Server Error

### ISSUE THREAD

**Issue by Sarthak-Agarwal1410** [plasmabio/tljh-repo2docker#55]
![image](https://user-images.githubusercontent.com/69386523/158477996-dd607403-bfa6-4bb5-b1a4-84b288c88028.png)

Error: HTTP 500: Internal Server Error (Error in Authenticator.pre_spawn_start: DockerError DockerError(400, 'no such image: None: invalid reference format: repository name must be lowercase'))

Commands used:

# install Docker
sudo apt update && sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
sudo apt update && sudo apt install -y docker-ce

# pull the repo2docker image
sudo docker pull quay.io/jupyterhub/repo2docker:main

# install TLJH
curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py \
  | sudo python3 - \
    --admin test:test \
    --plugin git+https://github.com/plasmabio/tljh-repo2docker@master

**Comment by mupsje** [comment]
same here

**Comment by avianinc** [comment]
Same here...
