### ISSUE TITLE
Homogenize environments names and directories

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/tljh-repo2docker#9]
The new environment panel management now exhibits the name of the environment:

![image](https://user-images.githubusercontent.com/733861/80727368-ec133300-8b05-11ea-8334-690279933f4a.png)

Default environment names are built upon URL of the repo and reference. For instance, repo URL `https://github.com/plasmabio/template-bash` and reference `master` produce env name `plasmabio/template-bash-master`. In the user home directory however, this environment is created in the `plasmabio-template-bash-master` directory.

It would be more intuitive for the end-users to have identical names for both the environment and the directory containing files of this environment.

**Comment by jtpio** [comment]
Indeed, we could use `plasmabio-template-bash-master` the env name and the folder name.

**Comment by pierrepo** [comment]
Yes. You're right.

**Comment by jtpio** [comment]
Also for now, PlasmaBio doesn't use the new name to create the folders yet, if a name was specified. It still creates them as `plasmabio-template-bash-master`.
